CLIENT/Controllers/MovimientoController.cs
using CLIENT.Models.ViewModels;
using CLIENT.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;

namespace CLIENT.Controllers
{
    public class MovimientoController : Controller
    {
        private readonly IServiceMovimientosTarjeta _serviceMovimientos;

        public MovimientoController(IServiceMovimientosTarjeta serviceMovimientos)
        {
            _serviceMovimientos = serviceMovimientos;
        }

        [HttpGet]
        public async Task<IActionResult> Listado(int id, string numeroTarjeta, int mes, int anio)
        {
            int tipo = 1;
            List<MovimientosTarjetaVM> movimientos = await _serviceMovimientos.ObtenerMovimientosTarjeta(id, numeroTarjeta, tipo, mes, anio);
            // Ordenar los movimientos por fecha de forma descendente (la más reciente primero)
            movimientos = movimientos.OrderByDescending(m => m.fechaMovimiento).ToList();
            return View(movimientos);
        }

        [HttpGet]
        public IActionResult Movimiento(int idTarjeta, int tipoMovimiento)
        {
            ViewBag.tipoMovimiento = tipoMovimiento;
            ViewBag.idTarjeta = idTarjeta;
            MovimientosTarjetaVM movimiento = new();
            movimiento.idTarjeta = idTarjeta;
            movimiento.tipoMovimiento = tipoMovimiento.ToString();
            movimiento.monto = 0;
            return View(movimiento);
        }

        [HttpPost]
        public async Task<IActionResult> Movimiento(MovimientosTarjetaVM movimiento)
        {

            if (!ModelState.IsValid)
            {
                return PartialView(movimiento);
            }
            try
            {

                if (movimiento.tipoMovimiento == "2")
                {
                    movimiento.monto = movimiento.monto * -1;
                }
                movimiento.fechaMovimiento = System.DateTime.Now;
                await _serviceMovimientos.GuardarMovimiento(movimiento);
                return Json(new { estado = "Todo bien" });
            }
            catch (Exception)
            {

                return Json(new { estado = "Error" });
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetExcelCompras(int id, string numeroTarjeta, int mes, int anio)
        {
            List<MovimientosTarjetaVM> movimientos = await _serviceMovimientos.ObtenerMovimientosTarjeta(id, numeroTarjeta, 1, mes, anio);

            using (var package = new ExcelPackage())
            {
                var worksheet1 = package.Workbook.Worksheets.Add("Compras");
                worksheet1.Cells["A1"].Value = "Fecha de Compra";
                worksheet1.Cells["B1"].Value = "Descripción";
                worksheet1.Cells["C1"].Value = "Monto";

                int row = 2;
                foreach (var movimiento in movimientos)
                {
                    worksheet1.Cells[$"A{row}"].Value = movimiento.fechaMovimiento.ToLongDateString();
                    worksheet1.Cells[$"B{row}"].Value = movimiento.descripcion;
                    worksheet1.Cells[$"C{row}"].Value = movimiento.monto.ToString("C");
                    row++;
                }
                worksheet1.Columns.AutoFit();
                worksheet1.Cells["A1:C1"].Style.Font.Bold = true;

                var stream = new MemoryStream();
                package.SaveAs(stream);

                // Set the stream position to the beginning
                stream.Position = 0;

                // Return the stream as a FileResult
                return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "ComprasTarjeta" + numeroTarjeta + DateTime.Now + ".xlsx");
            }
        }
    }
}

CLIENT/Controllers/TarjetaController.cs
using CLIENT.Models.ViewModels;
using CLIENT.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace CLIENT.Controllers
{
    public class TarjetaController : Controller
    {
        private readonly IServiceTarjeta _serviceTarjeta;
        private readonly IServiceMovimientosTarjeta _serviceMovimientos;

        public TarjetaController(IServiceTarjeta serviceTarjeta, IServiceMovimientosTarjeta serviceMovimientos)
        {
            _serviceTarjeta = serviceTarjeta;
            _serviceMovimientos = serviceMovimientos;
        }


        [HttpGet]
        public async Task<IActionResult> Detalles(int id, string numeroTarjeta)
        {
            TarjetaCreditoVM tarjeta = await _serviceTarjeta.getTarjetaInfo(id, numeroTarjeta);
            return View(tarjeta);
        }

        [HttpGet]
        public async Task<IActionResult> ImprimirEstadoCuenta(int id, string numeroTarjeta, int mes, int anio)
        {
            QuestPDF.Settings.License = LicenseType.Community;
            TarjetaCreditoVM tarjeta = await _serviceTarjeta.getTarjetaInfo(id, numeroTarjeta);
            List<MovimientosTarjetaVM> movimientos = await _serviceMovimientos.ObtenerMovimientosTarjeta(id, numeroTarjeta, 3, mes, anio);
            // Ordenar los movimientos por fecha de forma descendente (la más reciente primero)
            movimientos = movimientos.OrderByDescending(m => m.fechaMovimiento).ToList();
            var Data = Document.Create(document =>
            {
                document.Page(page =>
                {
                    page.Size(PageSizes.Letter.Portrait());
                    page.Margin(30);
                    page.Header().ShowOnce().Row(row =>
                    {
                        row.RelativeItem().Column(col =>
                        {
                            col.Item().Border(1).BorderColor("#FFFFFF").AlignCenter().Padding(5).Text("San Salvador " + DateTime.Now.ToLongDateString()).FontSize(8).FontColor("#000000");
                            col.Item().Border(1).BorderColor("#FFFFFF").Background("#FFFFFF").Padding(5).AlignCenter().Text("ESTADO DE CUENTA").FontColor("#000000").FontSize(10);
                            col.Item().Border(1).BorderColor("#FFFFFF").Padding(5).AlignCenter()
                            .Text(System.DateTime.Now.ToLongDateString()).FontSize(8).FontColor("#000000");
                        });
                    });
                    ///El contenido del reporte
                    page.Content().PaddingVertical(10).Column(col1 =>
                    {

                        col1.Item().Row(row1 =>
                        {
                            row1.RelativeItem().Column(col =>
                            {
                                col.Item().Text("Nombre titular").Bold().FontColor("#000000");

                                col.Item().Text(txt =>
                                {
                                    txt.Span(tarjeta.nombreTitular).FontSize(10).FontColor("#000000");
                                });

                                col.Item().Text("Número de tarjeta").Bold().FontColor("#000000");

                                col.Item().Text(txt =>
                                {
                                    txt.Span($"{tarjeta.numeroTarjeta}").FontSize(10).FontColor("#000000");
                                });
                            });

                            row1.RelativeItem().Column(col =>
                            {
                                col.Item().Text("Detalles").Bold().FontColor("#000000");

                                col.Item().Text(txt =>
                                {
                                    txt.Span($"Saldo actual: {tarjeta.saldoTotal.ToString("C")}").FontSize(10).FontColor("#000000");
                                });
                                col.Item().Text(txt =>
                                {
                                    txt.Span($"Saldo disponible: {tarjeta.disponible.ToString("C")}").FontSize(10).FontColor("#000000");
                                });
                                col.Item().Text(txt =>
                                {
                                    txt.Span($"Límite de crédito: {tarjeta.montoOtorgado.ToString("C")}").FontSize(10).FontColor("#000000");
                                });
                                col.Item().Text(txt =>
                                {
                                    txt.Span($"Cuota mínima: {tarjeta.cuotaMinima.ToString("C")}").FontSize(10).FontColor("#000000");
                                });
                                col.Item().Text(txt =>
                                {
                                    txt.Span($"Interés bonificable: {tarjeta.interesBonificable.ToString("C")}").FontSize(10).FontColor("#000000");
                                });
                                col.Item().Text(txt =>
                                {
                                    txt.Span($"Monto total con interés: {tarjeta.totalContadoConInteres.ToString("C")}").FontSize(10).FontColor("#000000");
                                });
                            });
                        });


                        col1.Item().PaddingTop(10).Column(col3 =>
                        {
                            col3.Item().Text("Estimado(a)(os) Sr(a)(es):").Bold().FontColor("#000000");

                            col3.Item().PaddingTop(5).Text(txt =>
                            {
                                txt.Span($"Adjuntamos el estado de cuenta con fecha de corte {System.DateTime.Now.ToLongDateString()} en el cual se detallan sus compras y pagos de su tarjeta de crédito").FontSize(10).FontColor("#000000");
                            });
                        });

                        ///Linea de separación
                        col1.Item().LineHorizontal(0.5f).LineColor("#000000");

                        ///Tabla de datos
                        col1.Item().Table(tabla =>
                        {
                            ///Definicion de las columnas
                            tabla.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn(2);
                                columns.RelativeColumn(2);
                                columns.RelativeColumn(2);
                            });

                            tabla.Header(header =>
                            {
                                header.Cell().Background("#F8F8FF").Padding(3)
                                .Text("Fecha").FontColor("#000000").FontSize(10);
                                header.Cell().Background("#F8F8FF").Padding(3)
                                .Text("Descripción").FontColor("#000000").FontSize(10);
                                header.Cell().Background("#F8F8FF").Padding(3)
                                .Text("Monto").FontColor("#000000").FontSize(10);
                            });

                            ///Llenar la informacion de la tabla
                            foreach (var movimiento in movimientos)
                            {
                                tabla.Cell().BorderBottom(0.5f).BorderColor("#000000")
                                .Padding(3).Text(movimiento.fechaMovimiento.ToLongDateString()).FontSize(8).FontColor("#000000");

                                tabla.Cell().BorderBottom(0.5f).BorderColor("#000000")
                                .Padding(3).Text(movimiento.descripcion).FontSize(8).FontColor("#000000");

                                tabla.Cell().BorderBottom(0.5f).BorderColor("#000000")
                                .Padding(3).Text(movimiento.monto.ToString("C")).FontSize(8).FontColor("#000000");
                            }
                        });

                        col1.Item().AlignRight().Text($"Total en movimientos: {movimientos.Sum(x => x.monto).ToString("C")}").FontSize(10).FontColor("#000000");

                      

                        col1.Spacing(10);
                    });
                    ///El footer del reporte
                    page.Footer().AlignRight().Text(txt =>
                    {
                        txt.Span("Página ").FontSize(10).FontColor("#000000");
                        txt.CurrentPageNumber().FontSize(10).FontColor("#000000");
                        txt.Span(" de ").FontSize(10).FontColor("#000000");
                        txt.TotalPages().FontSize(10).FontColor("#000000");
                    });
                });
            }).GeneratePdf();
            Stream stream = new MemoryStream(Data);
            return File(stream, "application/pdf", $"{numeroTarjeta}_Estado_Cuenta{DateTime.Now.ToShortDateString()}.pdf");
        }

    }
}

CLIENT/Views/Tarjeta/Detalles.cshtml
@{
    ViewData["Title"] = "Detalles";
}

@model CLIENT.Models.ViewModels.TarjetaCreditoVM

<div class="container-xl">
    <p class="fw-bold">Detalles de la tarjeta</p>
</div>

<div class="container-xl">
    <input type="hidden" id="numeroTarjeta" value="@Model.numeroTarjeta" />
    <div class="card shadow-lg p-3 detallesTarjeta">
        <div class="card-body">
            <div class="d-flex justify-content-between mb-4">
                <div>
                    <p class="card-title">Nombre titular en tarjeta</p>
                    <h3 class="card-text">@Model.nombreTitular</h3>
                </div>
                <div>
                    <p class="card-title">Número de Tarjeta</p>
                    <h3 class="card-text">@Model.numeroTarjeta</h3>
                </div>
            </div>
            <div class="d-flex justify-content-between mb-4">
                <div>
                    <p class="card-title">Saldo Disponible</p>
                    <h3 class="card-text">@Model.disponible.ToString("C")</h3>
                </div>
                <div>
                    <p class="card-title">Saldo Actual</p>
                    <h3 class="card-text">@Model.saldoTotal.ToString("C")</h3>
                </div>
                <div>
                    <p class="card-title">Límite Crédito</p>
                    <h3 class="card-text">@Model.montoOtorgado.ToString("C")</h3>
                </div>
            </div>
            <div class="row mb-4">
                <div class="col-6">
                    <p class="card-title">Cuota mínima</p>
                    <h3 class="card-text">@Model.cuotaMinima.ToString("C")</h3>
                </div>
                <div class="col-6">
                    <p class="card-title">Monto total con interés</p>
                    <h3 class="card-text">@Model.totalContadoConInteres.ToString("C")</h3>
                </div>
            </div>
            <div class="row mb-4">
                <div class="col-6">
                    <p class="card-title">Interés bonificable</p>
                    <h3 class="card-text">@Model.interesBonificable.ToString("C")</h3>
                </div>
            </div>
            <div class="d-flex justify-content-end gap-3">
                <button class="btn colorAtlantida text-light shadow-lg" onclick="OpenModalMovimiento(@Model.id, 1)">Comprar <i class="fas fa-credit-card ms-3"></i></button>
                @if (Model.saldoTotal == 0)
                {
                    <button class="btn colorAtlantida disabled text-light shadow-lg" onclick="OpenModalMovimiento(@Model.id, 2)">Pagar <i class="fas fa-credit-card ms-3"></i></button>
                }
                else
                {
                    <button class="btn colorAtlantida text-light shadow-lg" onclick="OpenModalMovimiento(@Model.id, 2)">Pagar <i class="fas fa-credit-card ms-3"></i></button>
                }
            </div>
        </div>
    </div>
    <div class="movimientosTarjeta mt-3">
        <p class="fw-bold">Detalle de compras</p>
        <div class="row mt-2 mb-2">
            <div class="col-lg-12 d-flex flex-column">
                <p class="text-secondary">Seleccione un filtro para los registros:</p>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="mes" id="mesActual" value="mesActual" checked>
                    <label class="form-check-label" for="mesActual">Mes presente</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="mes" id="mesPasado" value="mesPasado">
                    <label class="form-check-label" for="mesPasado">Mes pasado</label>
                </div>
            </div>
        </div>
        <div id="ListadoMovimientos" class="ListadoMovimientos"></div>
    </div>
</div>

<!-- Modal para agregar un pago o una compra -->
<div class="modal fade" id="ModalMovimiento" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <p class="modal-title" id="exampleModalLabel">Movimiento<br /></p>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modalCuerpoMovimiento"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        // Al cargar la vista mostraremos las compras de la tarjeta
        $(document).ready(function () {
            var fechaActual = new Date();
            var mesActual = fechaActual.getMonth() + 1;
            var anioActual = fechaActual.getFullYear();
            Listado(mesActual, anioActual);

            $('#mesActual, #mesPasado').change(function () {
                if ($(this).is(':checked')) {
                    // Ejecutar una función aquí cuando un radio button cambie
                    // Por ejemplo, puedes llamar a otra función o realizar alguna tarea específica
                    console.log("El radio button seleccionado es: " + $(this).val());
                }
            });
        });

        // Función para cargar el listado
        function Listado(mes, anio) {
            var url = '@Url.Action("Listado", "Movimiento")';
            url += '?id=' + encodeURIComponent(@Model.id) + '&numeroTarjeta=' + $('#numeroTarjeta').val() + "&mes=" + encodeURIComponent(mes) + "&anio=" + encodeURIComponent(anio);
            CallAsync("GET", url, "#ListadoMovimientos");
        }

        // Función para abrir el modal de movimientos
        function OpenModalMovimiento(id, tipo) {
            var url = '@Url.Action("Movimiento", "Movimiento")';
            url += '?idTarjeta=' + encodeURIComponent(id) + '&tipoMovimiento=' + encodeURIComponent(tipo);
            CallAsync("GET", url, "#modalCuerpoMovimiento");
            $('#ModalMovimiento').modal('show');
        }

        // Función para enviar los datos
        function SendDataFormAdd() {
            let form = $('#FormMovimiento').serialize();
            $.ajax({
                url: '@Url.Action("Movimiento", "Movimiento")',
                type: 'POST',
                data: form,
                headers: { "RequestVerificationToken": $('input[name="__RequestVerficationToken"]').val() },
                success: function (response) {
                    if (response.estado == "Error") {
                        alertify.error("Ha ocurrido un error");
                    } else if (response.estado == "Todo bien") {
                        alertify.success("Realizado con éxito");
                        $('#ModalMovimiento').modal('hide');
                        location.reload();
                    } else {
                        $('#modalCuerpoMovimiento').html(response);
                    }
                }
            });
        }

        // Exportar excel de compras
        function exportarExcel() {
            var fechaActual = new Date();
            var mes = fechaActual.getMonth() + 1;
            var anio = fechaActual.getFullYear();
            if ($('#mesPasado').is(':checked')) {
                mes = mes - 1;
            }
            var url = '@Url.Action("GetExcelCompras", "Movimiento")';
            url += '?id=' + encodeURIComponent(@Model.id) + '&numeroTarjeta=' + $('#numeroTarjeta').val() + "&mes=" + encodeURIComponent(mes) + "&anio=" + encodeURIComponent(anio);
            window.open(url, '_blank');
        }

        // Función para exportar el pdf del estado de cuenta del mes actual o pasado
        function exportarEstadoCuenta() {
            var fechaActual = new Date();
            var mes = fechaActual.getMonth() + 1;
            var anio = fechaActual.getFullYear();
            if ($('#mesPasado').is(':checked')) {
                mes = mes - 1;
            }
            var url = '@Url.Action("ImprimirEstadoCuenta", "Tarjeta")';
            url += '?id=' + encodeURIComponent(@Model.id) + '&numeroTarjeta=' + $('#numeroTarjeta').val() + "&mes=" + encodeURIComponent(mes) + "&anio=" + encodeURIComponent(anio);
            window.open(url, '_blank');
        }
    </script>
}